// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require("eslint-config-expo/flat");

module.exports = defineConfig([
  expoConfig,
  {
    // Orval output is regenerated by `npm run api:gen`; never lint or edit it.
    ignores: ["dist/*", "src/api/generated/**", "src/api/schemas.zod.ts"],
  }
]);
