/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Shop API
 * RN 마이그레이션 검증용 API. 에러는 HTTP 상태가 아니라 `code`로 분기한다.
 * OpenAPI spec version: 0.1.0
 */
import zod from 'zod';

/**
 * 무한 스크롤용. 다음 페이지 skip = skip + limit, 그 값이 total 이상이면 마지막 페이지다.
 * @summary 상품 목록 (offset 페이지네이션)
 */
export const listProductsQueryLimitDefault = 20;
export const listProductsQueryLimitMax = 50;export const listProductsQuerySkipDefault = 0;
export const listProductsQuerySkipMin = 0;
export const listProductsQuerySkipMax = 9007199254740991;

export const listProductsQueryParams = zod.object({
  "limit": zod.number().min(1).max(listProductsQueryLimitMax).default(listProductsQueryLimitDefault).describe('Page size (1–50)'),
  "skip": zod.number().min(listProductsQuerySkipMin).max(listProductsQuerySkipMax).optional().describe('Number of items to skip (offset)')
})

export const listProductsResponseItemsItemIdMin = -9007199254740991;
export const listProductsResponseItemsItemIdMax = 9007199254740991;export const listProductsResponseTotalMin = -9007199254740991;
export const listProductsResponseTotalMax = 9007199254740991;export const listProductsResponseSkipMin = -9007199254740991;
export const listProductsResponseSkipMax = 9007199254740991;export const listProductsResponseLimitMin = -9007199254740991;
export const listProductsResponseLimitMax = 9007199254740991;

export const listProductsResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.number().min(listProductsResponseItemsItemIdMin).max(listProductsResponseItemsItemIdMax),
  "title": zod.string(),
  "price": zod.number(),
  "discountPercentage": zod.number(),
  "rating": zod.number(),
  "thumbnail": zod.url(),
  "brand": zod.string().optional()
})),
  "total": zod.number().min(listProductsResponseTotalMin).max(listProductsResponseTotalMax),
  "skip": zod.number().min(listProductsResponseSkipMin).max(listProductsResponseSkipMax),
  "limit": zod.number().min(listProductsResponseLimitMin).max(listProductsResponseLimitMax)
})


/**
 * @summary 상품 상세
 */
export const getProductPathIdMax = 9007199254740991;

export const getProductParams = zod.object({
  "id": zod.number().min(1).max(getProductPathIdMax).describe('Product id')
})

export const getProductResponseIdMin = -9007199254740991;
export const getProductResponseIdMax = 9007199254740991;export const getProductResponseStockMin = -9007199254740991;
export const getProductResponseStockMax = 9007199254740991;

export const getProductResponse = zod.object({
  "id": zod.number().min(getProductResponseIdMin).max(getProductResponseIdMax),
  "title": zod.string(),
  "price": zod.number(),
  "discountPercentage": zod.number(),
  "rating": zod.number(),
  "thumbnail": zod.url(),
  "brand": zod.string().optional(),
  "description": zod.string(),
  "category": zod.string(),
  "images": zod.array(zod.url()),
  "stock": zod.number().min(getProductResponseStockMin).max(getProductResponseStockMax),
  "availabilityStatus": zod.string().optional(),
  "shippingInformation": zod.string().optional(),
  "warrantyInformation": zod.string().optional(),
  "returnPolicy": zod.string().optional()
})
